#!/bin/sh
set -x
set -e

NAME=$1
DOCKER_OPTS="$2"
STACKAGE_VARIETY='lts'
STACKAGE_VERSION='1.7'
VERSION="$(date -u +%Y%m%d-%H%MZ)-$STACKAGE_VARIETY-$STACKAGE_VERSION"
IMAGE_NAME="${NAME}-${VERSION}"
STACKAGE_URL="http://www.stackage.org/$STACKAGE_VARIETY/$STACKAGE_VERSION"
COMMIT=$(git rev-parse HEAD)
FINGERPRINT="${COMMIT}-$STACKAGE_VARIETY-$STACKAGE_VERSION"
USER="$UID"

if ! grep -q "^${FINGERPRINT}$" last-built; then
  mkdir -p cache
  rsync -a src/ cache
  docker $DOCKER_OPTS run -e LANG=C.UTF-8 \
                          -e STACKAGE_URL=$STACKAGE_URL \
                          --name="$IMAGE_NAME" \
                          -t -v ${PWD}/cache:/src:rw \
                          debian:jessie \
                          "/bin/bash" -c "/src/install ; chown -R $USER /src"
  docker $DOCKER_OPTS commit "$IMAGE_NAME" "anchor/${NAME}:${VERSION}"
  docker $DOCKER_OPTS rm "$IMAGE_NAME" || true
  docker $DOCKER_OPTS tag -f "anchor/${NAME}:${VERSION}" "anchor/${NAME}:latest"
  docker $DOCKER_OPTS push "anchor/${NAME}:latest"
  echo "${FINGERPRINT}" > last-built
fi
