#!/bin/sh
set -x
set -e

echo "LANG=C.UTF-8" > /etc/default/locale

cd /src

apt-get update -q -y
apt-get install -q -y wget

if grep "8." /etc/debian_version; then
    echo jessie
elif grep "7." /etc/debian_version; then
    echo wheezy
    wget http://packages.engineroom.anchor.net.au/ANCHOR-GPG-KEY
    apt-key add ANCHOR-GPG-KEY
    tee -a /etc/apt/sources.list.d/feature-zeromq.list <<EOF
deb [ arch=amd64 ] http://packages.engineroom.anchor.net.au/feature/zeromq/debian wheezy zeromq
EOF
        tee -a /etc/apt/sources.list.d/feature-libsodium.list <<EOF
deb [ arch=amd64 ] http://packages.engineroom.anchor.net.au/feature/libsodium/debian wheezy libsodium
EOF
else
    echo "Unexpected version, exiting"
    exit 1
fi

apt-get update -q -y
cat apt-packages | xargs apt-get install -q -y

curl -O https://www.haskell.org/ghc/dist/7.8.4/ghc-7.8.4-x86_64-unknown-linux-deb7.tar.bz2
tar xf ghc-7.8.4-x86_64-unknown-linux-deb7.tar.bz2
cd ghc-7.8.4
./configure
make install

cd /src
mkdir -p cabal
cd cabal

rm -rf /usr/local/share/doc

mkdir /root/.cabal
cp /src/.cabal/config /root/.cabal/config

cd /src

wget "${STACKAGE_URL}/cabal.config?global=true" -O cabal.config
cat "cabal.config" >> /root/.cabal/config
rm cabal.config

# snap-server supports SSL. This is turned off by default though.
echo "constraint: snap-server +openssl" >> /root/.cabal/config
echo "constraint: mtl-compat +two-point-one" >> /root/.cabal/config

# Prepare cabal-install (hacky way through debian cabal-install)
apt-get download cabal-install
dpkg --force-all -i cabal-install*.deb
cabal update
cabal install -j --global cabal-install
apt-get remove -y cabal-install

# alex, happy and other tools
cat cabal-tools | tr "\n" "\0" | xargs -0 cabal install -j --global

echoerr() { echo "$@" 1>&2; }

# preinstalled packages
cat cabal-packages | while read p ; do
  if grep -q $p "/root/.cabal/config" ;
  then echo $p ;
  else echoerr "Dropping package" $p "as it is not on Stackage." ;
  fi ;
done | tr "\n" "\0" | xargs -0 cabal install -j --global
