#!/bin/sh
set +x
set +e

export HOME=/src
export PATH=/src/.cabal/bin:$PATH

cd /src

apt-get update
cat apt-packages | xargs apt-get install

cabal update
cabal install 'mtl>=2.2'

STACKAGE_URL=$(curl http://www.stackage.org/alias/fpcomplete/unstable-ghc78-inclusive -s -L -I -o /dev/null -w '%{url_effective}')
STACKAGE="remote-repo: stackage-ghc78-inc:${STACKAGE_URL}"
echo $STACKAGE | cat - .cabal/config > /tmp/out && mv /tmp/out .cabal/config
cabal update

cat cabal-tools | tr "\n" "\0" | xargs -0 cabal install --global
cat cabal-packages | tr "\n" "\0" | xargs -0 cabal install --global
