#!/bin/sh
set +x
set +e

echo "LANG=C.UTF-8" > /etc/default/locale

cd /src

apt-get update -q -y
apt-get dist-upgrade -q -y
cat apt-packages | xargs apt-get install -q -y

wget https://www.haskell.org/ghc/dist/7.8.4/ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz
tar xf ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz
cd ghc-7.8.4
./configure
make install

rm /usr/local/bin/haddock*
rm -rf /usr/local/share/doc

mkdir /root/.cabal
cp /src/.cabal/config /root/.cabal/config

cd /src

cabal update
wget "${STACKAGE_URL}/cabal.config?global=true"
cat "cabal.config?global=true" >> /root/.cabal/config

# Stackage still has an old version of mtl.
# The packages responsible seem okay to ignore for us though.
# https://github.com/fpco/stackage/issues/217
sed -i -Ee "s#^constraint: mtl ==(.*)\$#constraint: mtl >=2.2.1#" /root/.cabal/config
sed -i -Ee "s#^constraint: transformers (.*)\$#constraint: transformers ==0.4.*#" /root/.cabal/config

# snap-server supports SSL. This is turned off by default though.
echo "constraint: snap-server +openssl" >> /root/.cabal/config

cabal update

# alex, happy and other tools
cat cabal-tools | tr "\n" "\0" | xargs -0 cabal install --global

echoerr() { echo "$@" 1>&2; }

# preinstalled packages
cat cabal-packages | while read p ; do
  if grep -q $p "cabal.config?global=true" ;
  then echo $p ;
  else echoerr "Dropping package" $p "as it is not on Stackage." ;
  fi ;
done | tr "\n" "\0" | xargs -0 cabal install --global
